# Generated by Django 4.1.1 on 2022-10-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templater", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="template_author",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
